name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  demo-001:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: im running demo
        run: echo "Im running demo"
        shell: bash
  third-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: "i'm just test"
        run: |
            echo "First Stept"
            echo "Second Stept"
